USE `Cheep`;

DELETE FROM USER;
DELETE FROM ITEM;
DELETE FROM LOCATION;
DELETE FROM ITEM_LOCATION_PRICE;
DELETE FROM `LIST`;

-- REGISTER USER

-- ADD ITEM
-- VIEW ITEMS
-- ADD LOCATION
-- VIEW LOCATIONS
-- ADD ITEM-KOCATION-PRICE
-- VIEW ILP
-- ADD LIST
-- ADD ILP TO LIST
-- VIEW LIST