# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc3af8713ae1e656e86dd2d00dab188064ef120104e76a8b924e685c889dec46db8938f5aeb6fc7ea0613f9504f778f939eecf23609a169672ec7d40575707f2

test:
  secret_key_base: 2c4637a0208260b250e9a68599bb37dc2149cd9afa59a8f76079d603433bfa46618e5c52d63576025179bdb9852888c7a006230ed32f6e25f0784967baf259ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
